E1 = {"error":"Day Limit"}
E2 = {"msg": "OTP SENT"}
E3 = {"msg":"Verification Success"}
E4 = {"error":"Invalid OTP"}
E5 = {"msg":"Resent OTP"}
E6 = {"error":"INVALID Number! OTP NOT SENT"}
E7 = {"error":"Invalid Signature"}
EXE = {"error":"Exception"}
E9 = [True,'Email and Mobile Already Registered']
E10 = [True,'Email Already Registered']
E11 = [True,'Mobile Already Registered']
E12 = [False,'Both Mobile And Number Unregistered']
E13 = {"error": "* Marked Fields are compulsory"}
E14 = {"error": "Invalid Mobile Number"}
E15 = {"error": "Invalid Data Type"}
E16 = {"error": "Authorization Missing"}
E17 = {"error": "Invalid Authorization"}
E18 = {"error": "Not Logged In"}
E19 = {"message": "Logged In"}
E20 = {"error": "Account Does Not Exist"}
E21 = {"error": "Invalid Password"}